### ISSUE TITLE
nautobot-welcome-wizard dashboard 

### ISSUE THREAD

**Issue by JyceBera** [nautobot/nautobot-app-welcome-wizard#101] opened 2024-03-05 00:55 UTC
### Environment
* Python version: 3.10.12
* Nautobot version:  2.1.5 , 2.1.6
* nautobot-welcome-wizard version:  2.0.0

### Expected Behavior
![image](https://github.com/nautobot/nautobot-app-welcome-wizard/assets/162236304/8350e31a-13f2-458d-bfee-704274f572fa)

### Observed Behavior
![image](https://github.com/nautobot/nautobot-app-welcome-wizard/assets/162236304/b5a9d7a2-8d53-4047-aa1d-45c8bfdc264a)

### Steps to Reproduce
1.Upgrade from a previous version < 2.1.5
2.Uninstall nautobot-welcome-wizard plugin
3.Force reinstall : pip install nautobot-welcome-wizard --force-reinstall

Same odd behaviour
### Resolution
Launch: nautobot-server nbshell

delete : Merlin.objects.filter(nautobot_list_link="dcim:site_list").delete()
delete : Merlin.objects.filter(nautobot_list_link="dcim:devicerole_list").delete()

Lots of thanks @joewesch

**Comment by joewesch** [comment] 2024-03-05 17:30
I was able to reproduce this and confirm with the following steps:
- Install a fresh Nautobot v1 instance and Welcome Wizard v1.1.4
- Navigate to the WW Dashboard to get the Merlin objects auto populated in the DB
- Upgrade Nautobot to v2 and Welcome Wizard v2.0.0
- Error occurs when you Navigate to the WW Dashboard again

**Comment by joewesch** [comment] 2024-03-05 18:02
It looks like we already have PR #94 waiting to get merged to fix this.

**Comment by smk4664** [comment] 2024-05-31 03:43
This issue was resolved as of 2.0.1

**Closed by smk4664** 2024-05-31 03:43 UTC
